liongram/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
from django.urls import path,include

from posts.views import index,url_view, url_parameter_view, function_view,class_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', function_view),
    path('cbv/', class_view.as_view()), #얘는 클래스라서 as view를 입력해줘야함
    
    path('', index, name='index'),
    path('posts/', include('posts.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

liongram/posts/urls.py
from django.urls import path

from .views import post_list_view, post_create_view,post_update_view, post_detail_view, post_delete_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    path('create/', post_create_view, name='post-create'),
    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view),
    path('<int:id>/delete/', post_delete_view),
    ]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name= '내용')
    created_at = models.DateTimeField(verbose_name='작성일', auto_now_add=True)
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer= models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)
    #blank값은 공백을 허용할 것인가, null값은 null값을 허용할 것인가? 
    #1대 다 관계에서는 Foreignkey를 필수로 쓰고 to 속성과 on_delete속성을 넣어줘야한다! 
    
class Comment(models.Model):
    content = models.TextField(verbose_name='내용')
    created_at = models.DateTimeField(verbose_name='작성일')
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE)

liongram/posts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse , JsonResponse

from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

from .models import Post

def index(request): 
    post_list = Post.objects.all().order_by('-created_at') #post 전체 데이터 조회 
    #all()뒤에 .all().order_by('-created_at')를 넣으면 만들어진 순으로 (최신순으로)보여줌
    context = {
        'post_list': post_list,    
    }
    return render(request, 'index.html', context)


def post_list_view(request):
    post_list = Post.objects.all() #post 전체 데이터 조회 
    post_list = Post.objects.filter(writer=request.user) 
    #Post.wirter가 현재 로그인인 것 조회 
     
    context = {
        'post_list': post_list,    
    }
    return render(request, 'posts/post_list.html', context)

def post_detail_view(request, id):
    try:
        post = Post.objects.get(id=id)
    except Post.DoesNotExist:
        return redirect('index')
    context = {
        'post': post,    
    }
    return render(request, 'posts/post_detail.html', context)

def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(
            image=image,
            content=content,
            writer=request.user
        )
        return redirect('index')
    
#맨 마지막에 redirect를 하면 초록색으로 뜸! 

def post_update_view(request, id):
    return render(request, 'posts/post_form.html')

def post_delete_view(request, id):
    return render(request, 'posts/post_confirm_delete.html')

# Create your views here.
def url_view(request):
    print('url_view()')
    data = { 'code': '001', 'msg':'OK'}
    return HttpResponse('<h1>url_view</h1>')
    # return JsonResponse(data)

def url_parameter_view(request,username):
    print('url_parameter_view()')
    # print(username)
    # print(request.GET)
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    return HttpResponse(username)
#요청해서 받을 수 있는 건
# 경로를 사용하거나 쿼리스트링과 쿼리파라미터를 활용하면 된다! 

def function_view(request):
    print(f'request.method: {request.method}')

    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')
#여기서 view_html은 템플릿이름을 말하는것임! 

class class_view(ListView): 
    model = Post
    ordering = ['-id']
    template_name = 'cbv_view.html'

def function_list_view(request):
    #함수기반뷰는 우리가 직접 모든걸 작성해야함. 
    #대신 코드가 직관적임
    object_list = Post.objects.all().order_by('-id')
    return render(request, 'cbv_view.html', {'object_list' : object_list })

liongram/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        <p>{{ object }}</p>
    {% endfor %}
    <!-- object리스트를 반복해주고 반복할때마다 저 object를 출력해줌 -->
</body>
</html>

liongram/posts/templates/view.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <a href="/fbv/">새로고침</a><br>

    <form action="" method="GET">
        <input type="text" name="var">
        <input type="submit" value="GET 제출">
    </form>
<!-- GET, POST를 쓸 때 대문자는 상관없음 -->
    <form action="" method="POST"> {% csrf_token %}
        <input type="text" name="var">
        <input type="submit" value="POST 제출">
    </form>

</body>
</html>
<!-- GET은 일반적으로 데이터 또는 리소스를 받을때. 
    POST 데이터 추가, 수정, 또는 삭제할 때 사용   -->
<!-- !누르고 엔터 누르면 html기본 템플릿 자동완섬됨 -->

liongram/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body class="container">
    <div>
    {% block content %}
    {% endblock %}
    </div>
    <div>
        <ul class = "bottom-menu-group">
            <li>
                <img src="{% static 'icons/home.png' %}" alt="홈"> 
            </li>
            <li>
                <img src="{% static 'icons/search.png' %}" alt="검색">
            </li>
            <li>
                <a href="{% url 'posts:post-create' %}">
                <img src="{% static 'icons/add.png' %}" alt="글쓰기">
                </a>
            </li>
            <li>
                <img src="{% static 'icons/favorite.png' %}" alt="좋아요">
            </li>
            <li>
                <img src="{% static 'icons/person.png' %}" alt="프로필">
            </li>
        </ul>
    </div>
</body>
</html>

liongram/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}홈{% endblock %}


{% block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' with detail=False %}
        {% endfor %}
    </div>
</main>
{% endblock %}

liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <img src="http://via.placeholder.com/32x32" alt="프로필이미지">
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>
    </div>
    <div class="card__body">
        <div>
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}" alt="">
            {% else %}
                <img class="card__image" src="http://via.placeholder.com/600X600" alt="">
            {% endif %}
        </div>
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite.png' %}" alt="좋아요">
                <img class="card__btn" src="{% static 'icons/comment.png' %}" alt="댓글">
                <img class="card__btn" src="{% static 'icons/send.png' %}" alt="공유하기">
            </div>
        <img class="card__btn" src="{% static 'icons/bookmark.png' %}" alt="북마크">
    </div>
    <div class="card_content">
        <span class="card__like-num">좋아요 00개</span>
        <div class="card__main-text">
            <p><span class="card__user-name">{{ post.writer }}</span>{{post.content|truncatechars:35}}</p>
                {% if not detail %}
                    {{post.content|truncatechars:35}}
                {% else %}
                    {{post.content}}
                {% endif %}
                </p>
            {% if not detail %}
                <a href="{% url 'posts:post-detail' post.id %}">더보기</a>
            {% endif %}
        </div>
        <div>
            <p>댓글 {{ post.comment_set.all.count }}개
            {% if not detail %}
                <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
            {% endif %}
            </p>
            <ul class="card__comment-group"> 
                {% if not detail %}
                    {% for comment in post.comment_set.all|slice:":2" %}
                    <li>
                        <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                    </li>
                    {% endfor %}
                {% else %}
                    {% for comment in post.comment_set.all %}
                    <li>
                        <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p>
                    </li>
                    {% endfor %}
                {% endif %}
            </ul>
            <p class="card__created-at">{{post.created_at|date:"Y년 m월 d일"}}</p>
        </div>
    </div>
</div>

liongram/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}글 삭제{% endblock %}


{% block content %}
<h1>Post 삭제 화면</h1>
{% endblock %}

liongram/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %}글 상세{% endblock %}


{% block content %}
<h1>Post 상세  화면</h1>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

liongram/templates/posts/post_form.html
{% extends 'base.html' %}
{% block title %}글 입력{% endblock %}

{% block content %}
<h1>Post 입력 화면</h1>
<form action="{% url 'posts:post-create' %}" method="POST"> {% csrf_token %}

    <div>
        <label for="id_image">이미지</label>
        <input type="file" name="image" accept="image/*" id="id_image"> 
    </div>
    <div>
        <label for="id_content">내용</label>
        <textarea name="content" id="id_content" cols="30" rows="10"></textarea> 
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

liongram/templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %}글 목록{% endblock %}


{% block content %}
<h1>Post 목록 화면</h1>
<!-- {{ post_list }} -->

{% for post in post_list %}
    <div>
        {{ post.id }}<br/>
        {{ post.image }}<br/>
        {{ post.content }}<br/>
        {{ post.created_at }}<br/>
        {{ post.writer }}   <br/>
    </div>
{% endfor %}
{% endblock %}